spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/gaming?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.laven.gaming.server.database.domain
  mapper-locations: classpath:mapper/*.xml
